const productImages = [
  ["/assets/images/final/KS_03827.JPG", "/assets/images/final/KS_03830.jpg", "/assets/images/final/KS_03833.jpg"],
  ["/assets/images/final/KS_03871.JPG", "/assets/images/final/KS_03872.jpg", "/assets/images/final/KS_03873.jpg"],
  ["/assets/images/final/KS_03915.jpg", "/assets/images/final/KS_03916.jpg", "/assets/images/final/KS_03917.jpg"],
  ["/assets/images/final/KS_03936.JPG", "/assets/images/final/KS_03952.jpg", "/assets/images/final/KS_03953.jpg"],
  ["/assets/images/final/KS_03954.JPG", "/assets/images/final/KS_03956.jpg", "/assets/images/final/KS_03957.jpg"],
  ["/assets/images/final/KS_03975.JPG", "/assets/images/final/KS_03975-1.JPG", "/assets/images/final/KS_03976.jpg", "/assets/images/final/KS_03977.jpg"],
  ["/assets/images/final/KS_04039.JPG", "/assets/images/final/KS_04047.JPG", "/assets/images/final/KS_04053.JPG"],
  ["/assets/images/final/KS_04057.jpg", "/assets/images/final/KS_04064.jpg", "/assets/images/final/KS_04067.JPG"],
  ["/assets/images/final/KS_04069.jpg", "/assets/images/final/KS_04076.JPG", "/assets/images/final/KS_04088.jpg", "/assets/images/final/KS_04089.jpg"],
  ["/assets/images/final/KS_04105.JPG", "/assets/images/final/KS_04108.jpg", "/assets/images/final/KS_04110.JPG"],
  ["/assets/images/final/KS_04121.jpg", "/assets/images/final/KS_04122.jpg", "/assets/images/final/KS_04123.JPG"],
  ["/assets/images/final/KS_04125.JPG", "/assets/images/final/KS_04126.JPG", "/assets/images/final/KS_04127.jpg"],
  ["/assets/images/final/KS_04145.jpg", "/assets/images/final/KS_04145 1.jpg", "/assets/images/final/KS_04145 2.jpg", "/assets/images/final/KS_04145 3.jpg", "/assets/images/final/KS_041452 copy.jpg"],
  ["/assets/images/final/KS_04146.jpg", "/assets/images/final/KS_04147.jpg", "/assets/images/final/KS_04155.jpg"],
  ["/assets/images/final/KS_04157.jpg", "/assets/images/final/KS_04170.JPG", "/assets/images/final/KS_04172.jpg"],
  ["/assets/images/final/KS_04173.jpg", "/assets/images/final/KS_04198.JPG", "/assets/images/final/KS_04201.JPG", "/assets/images/final/KS_04203.jpg", "/assets/images/final/KS_04204.jpg"],
];

const sizeVariants = (id, imageId) =>
  ["S", "M", "L", "XL", "XXL"].map((size, index) => ({
    variant_id: `${id}${index + 1}`.padStart(4, "0"),
    id: `${id}.${index + 1}`,
    sku: `DS-${id}-${size}`,
    size,
    color: "default",
    image_id: imageId,
  }));

const createProduct = ({ id, title, description, price, tags, stock = 10 }) => ({
  id,
  title,
  description,
  type: "fashion",
  brand: "Dream Stitch",
  collection: ["all products"],
  category: "Men",
  price,
  sale: false,
  discount: "0",
  stock,
  new: false,
  tags,
  variants: sizeVariants(id, id * 100 + 1),
  images: productImages[id - 1].map((src, index) => ({
    image_id: id * 100 + index + 1,
    id: `${id}.${index + 1}`,
    alt: `${title} ${index === 0 ? "front" : index === 1 ? "side" : "detail"}`,
    src,
  })),
});

const products = [
  createProduct({
    id: 1,
    title: "Jodhpuri Style Suit",
    description: "A refined Jodhpuri style outfit with a Masuri fabric upper and a raw silk inner, finished with elegant embroidery for a polished ceremonial look.",
    price: 20000,
    stock: 8,
    tags: ["jodhpuri", "masuri", "raw silk", "embroidered", "formal"],
  }),
  createProduct({
    id: 2,
    title: "Black Handwork Sherwani - 5 Piece",
    description: "A complete five-piece black sherwani made from Masuri fabric with detailed handwork, paired with a raw silk inner suit for a regal groom-ready finish.",
    price: 35000,
    stock: 6,
    tags: ["sherwani", "black", "5 piece", "masuri", "handwork", "raw silk"],
  }),
  createProduct({
    id: 3,
    title: "Off-White Handwork Sherwani - 5 Piece",
    description: "A graceful off-white five-piece sherwani crafted in Masuri fabric with fine handwork and a raw silk inner suit, designed for weddings and formal celebrations.",
    price: 35000,
    stock: 6,
    tags: ["sherwani", "off white", "5 piece", "masuri", "handwork", "raw silk"],
  }),
  createProduct({
    id: 4,
    title: "Hand Embroidered Sherwani - 5 Piece",
    description: "A premium five-piece sherwani on plain fabric, elevated with complete handwork embroidery for a rich, traditional, and highly detailed formal statement.",
    price: 70000,
    stock: 4,
    tags: ["sherwani", "5 piece", "hand embroidery", "premium", "wedding"],
  }),
  createProduct({
    id: 5,
    title: "Velvet Masuri Sherwani - 7 Piece",
    description: "A luxurious seven-piece sherwani featuring velvet Masuri fabric, tailored for a commanding wedding look with depth, texture, and classic elegance.",
    price: 45000,
    stock: 5,
    tags: ["sherwani", "7 piece", "velvet", "masuri", "wedding"],
  }),
  createProduct({
    id: 6,
    title: "Jamawar Handwork Sherwani - 5 Piece",
    description: "A five-piece sherwani in rich Jamawar fabric with complete handwork, combining traditional pattern, premium texture, and refined occasion wear tailoring.",
    price: 50000,
    stock: 5,
    tags: ["sherwani", "5 piece", "jamawar", "handwork", "formal"],
  }),
  createProduct({
    id: 7,
    title: "Jodhpuri Style 3 Piece Suit - Cotton Silk",
    description: "A smart three-piece Jodhpuri style suit with a Masuri upper and cotton silk inner, made for men who want a sharp ethnic-formal silhouette.",
    price: 23000,
    stock: 8,
    tags: ["jodhpuri", "3 piece", "masuri", "cotton silk", "formal"],
  }),
  createProduct({
    id: 8,
    title: "Jodhpuri Style 3 Piece Suit - Raw Silk",
    description: "A sophisticated three-piece Jodhpuri suit featuring a Masuri upper and raw silk inner, tailored for weddings, receptions, and formal evenings.",
    price: 23000,
    stock: 8,
    tags: ["jodhpuri", "3 piece", "masuri", "raw silk", "formal"],
  }),
  createProduct({
    id: 9,
    title: "Indian Zari Hand Embroidered Sherwani - 5 Piece",
    description: "A five-piece sherwani made from Indian zari cloth with hand embroidery, giving the outfit a festive shine and detailed traditional character.",
    price: 30000,
    stock: 6,
    tags: ["sherwani", "5 piece", "indian zari", "hand embroidery", "wedding"],
  }),
  createProduct({
    id: 10,
    title: "Plain Fabric Handwork Sherwani",
    description: "A distinguished sherwani on plain fabric with intricate handwork embroidery, designed for a clean yet luxurious groom and occasion wear look.",
    price: 60000,
    stock: 4,
    tags: ["sherwani", "plain fabric", "handwork", "embroidered", "premium"],
  }),
  createProduct({
    id: 11,
    title: "Jodhpuri Style 5 Piece Suit",
    description: "A complete five-piece Jodhpuri style suit with an Indian zari upper and raw silk inner, made for a bold, royal, and polished formal presence.",
    price: 30000,
    stock: 6,
    tags: ["jodhpuri", "5 piece", "indian zari", "raw silk", "formal"],
  }),
  createProduct({
    id: 12,
    title: "Multi-Color Jodhpuri Style 3 Piece Suit",
    description: "A standout three-piece Jodhpuri style suit with a multi-color Masuri upper and raw silk inner, ideal for festive events and statement dressing.",
    price: 25000,
    stock: 7,
    tags: ["jodhpuri", "3 piece", "multi color", "masuri", "raw silk"],
  }),
  createProduct({
    id: 13,
    title: "Double Style Masuri Waistcoat Set",
    description: "A double style Masuri waistcoat paired with a cotton silk kurta, balancing traditional fabric detail with a clean, modern festive look.",
    price: 18000,
    stock: 9,
    tags: ["waistcoat", "masuri", "cotton silk", "kurta", "formal"],
  }),
  createProduct({
    id: 14,
    title: "Double Press Coat 2 Piece Suit",
    description: "A sharp two-piece suit with a double press coat, tailored for formal occasions where structure, simplicity, and a clean fit matter.",
    price: 23000,
    stock: 8,
    tags: ["2 piece", "suit", "double press coat", "formal"],
  }),
  createProduct({
    id: 15,
    title: "Classic 3 Piece Suit",
    description: "A classic three-piece suit with clean tailoring and versatile styling, suitable for formal gatherings, office events, and special occasions.",
    price: 18000,
    stock: 10,
    tags: ["3 piece", "suit", "classic", "formal"],
  }),
  createProduct({
    id: 16,
    title: "Formal 3 Piece Suit",
    description: "A refined three-piece suit designed for a confident formal look, offering a balanced fit, clean finish, and timeless menswear appeal.",
    price: 18000,
    stock: 10,
    tags: ["3 piece", "suit", "formal", "menswear"],
  }),
];

module.exports = products;
